"""当前用于业务闭环验证的三十笔手写模拟订单。"""


ORDERS = {
    "1001": {
        "order_id": "1001",
        "product_name": "头戴式 HiFi 耳机",
        "purchased_at": "2026-09-12",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1002": {
        "order_id": "1002",
        "product_name": "入耳式 HiFi 耳机",
        "purchased_at": "2026-09-08",
        "shipping_status": "已签收",
        "received_at": "2026-09-10",
        "refund_status": None,
    },
    "1003": {
        "order_id": "1003",
        "product_name": "开放式 HiFi 耳机",
        "purchased_at": "2026-09-15",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1004": {
        "order_id": "1004",
        "product_name": "无线 HiFi 耳机",
        "purchased_at": "2026-09-14",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1005": {
        "order_id": "1005",
        "product_name": "监听式 HiFi 耳机",
        "purchased_at": "2026-09-13",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1006": {
        "order_id": "1006",
        "product_name": "头戴式 HiFi 耳机",
        "purchased_at": "2026-09-12",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1007": {
        "order_id": "1007",
        "product_name": "入耳式 HiFi 耳机",
        "purchased_at": "2026-09-11",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1008": {
        "order_id": "1008",
        "product_name": "开放式 HiFi 耳机",
        "purchased_at": "2026-09-10",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1009": {
        "order_id": "1009",
        "product_name": "无线 HiFi 耳机",
        "purchased_at": "2026-09-09",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1010": {
        "order_id": "1010",
        "product_name": "监听式 HiFi 耳机",
        "purchased_at": "2026-09-08",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1011": {
        "order_id": "1011",
        "product_name": "头戴式 HiFi 耳机",
        "purchased_at": "2026-09-07",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1012": {
        "order_id": "1012",
        "product_name": "入耳式 HiFi 耳机",
        "purchased_at": "2026-09-06",
        "shipping_status": "未发货",
        "received_at": None,
        "refund_status": None,
    },
    "1013": {
        "order_id": "1013",
        "product_name": "开放式 HiFi 耳机",
        "purchased_at": "2026-09-13",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1014": {
        "order_id": "1014",
        "product_name": "无线 HiFi 耳机",
        "purchased_at": "2026-09-12",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1015": {
        "order_id": "1015",
        "product_name": "监听式 HiFi 耳机",
        "purchased_at": "2026-09-11",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1016": {
        "order_id": "1016",
        "product_name": "头戴式 HiFi 耳机",
        "purchased_at": "2026-09-10",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1017": {
        "order_id": "1017",
        "product_name": "入耳式 HiFi 耳机",
        "purchased_at": "2026-09-09",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1018": {
        "order_id": "1018",
        "product_name": "开放式 HiFi 耳机",
        "purchased_at": "2026-09-08",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1019": {
        "order_id": "1019",
        "product_name": "无线 HiFi 耳机",
        "purchased_at": "2026-09-07",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1020": {
        "order_id": "1020",
        "product_name": "监听式 HiFi 耳机",
        "purchased_at": "2026-09-06",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1021": {
        "order_id": "1021",
        "product_name": "头戴式 HiFi 耳机",
        "purchased_at": "2026-09-05",
        "shipping_status": "已发货运输中",
        "received_at": None,
        "refund_status": None,
    },
    "1022": {
        "order_id": "1022",
        "product_name": "入耳式 HiFi 耳机",
        "purchased_at": "2026-09-13",
        "shipping_status": "已签收",
        "received_at": "2026-09-14",
        "refund_status": "申请中",
    },
    "1023": {
        "order_id": "1023",
        "product_name": "开放式 HiFi 耳机",
        "purchased_at": "2026-09-11",
        "shipping_status": "已签收",
        "received_at": "2026-09-13",
        "refund_status": None,
    },
    "1024": {
        "order_id": "1024",
        "product_name": "无线 HiFi 耳机",
        "purchased_at": "2026-09-09",
        "shipping_status": "已签收",
        "received_at": "2026-09-12",
        "refund_status": None,
    },
    "1025": {
        "order_id": "1025",
        "product_name": "监听式 HiFi 耳机",
        "purchased_at": "2026-09-07",
        "shipping_status": "已签收",
        "received_at": "2026-09-11",
        "refund_status": None,
    },
    "1026": {
        "order_id": "1026",
        "product_name": "头戴式 HiFi 耳机",
        "purchased_at": "2026-09-05",
        "shipping_status": "已签收",
        "received_at": "2026-09-10",
        "refund_status": None,
    },
    "1027": {
        "order_id": "1027",
        "product_name": "入耳式 HiFi 耳机",
        "purchased_at": "2026-09-03",
        "shipping_status": "已签收",
        "received_at": "2026-09-09",
        "refund_status": None,
    },
    "1028": {
        "order_id": "1028",
        "product_name": "开放式 HiFi 耳机",
        "purchased_at": "2026-09-01",
        "shipping_status": "已签收",
        "received_at": "2026-09-08",
        "refund_status": None,
    },
    "1029": {
        "order_id": "1029",
        "product_name": "无线 HiFi 耳机",
        "purchased_at": "2026-08-30",
        "shipping_status": "已签收",
        "received_at": "2026-09-07",
        "refund_status": None,
    },
    "1030": {
        "order_id": "1030",
        "product_name": "监听式 HiFi 耳机",
        "purchased_at": "2026-08-25",
        "shipping_status": "已签收",
        "received_at": "2026-09-01",
        "refund_status": None,
    },
}
